### PR TITLE
Add GitLab Pages API integration

### PR DESCRIPTION
**Pull request by travismiller**
This pull request enables automatically submitting the generated Let's Encrypt certificate to the GitLab Pages domain through the GitLab API.

## Additions

* `--auto` option to utilize the new [Pages domains API](https://docs.gitlab.com/ce/api/pages_domains.html) endpoint. It cannot be used in conjuction with `--staging` as GitLab does not allow invalid certificates.
* `--gitlab` option to specify an alternate GitLab instance.

## Changes

* Domains that do not already exist in the project are added before beginning the ACME process.

## References

* Issue #30

### CODE REVIEW

**Comment by rolodato** [comment]
Hi @travismiller, thanks for putting this together, looks great! I'm reviewing it in more detail now.

**Comment by rolodato** [comment]
I'm thinking it might make sense to make the following breaking changes at this point:

* Remove the `--auto` option and always use GitLab's API to upload certs. Unless there are issues with GitLab's API I don't see why this option would not be used.
* The `--staging` flag can be renamed to `--dryrun`, since this captures the intent better. It would use LE's staging environment and not upload a cert to GitLab. Maybe there's a better wording than `--dryrun` since this wouldn't be technically 100% free of side effects (still commits to repository and does a staging LE challenge) but I think it's the closest and most widely-used term.
* Remove the `--gitlab` option and have `--repository` take the full URL to the user's repository, e.g. `--repository https://gitlab.com/user/repo` or `--repository https://gitlab.example.com/user/repo`, that way we don't need a special case for gitlab.com.

Let me know if this makes sense to you as well. I can fix up the README afterwards so don't worry about that. Thanks again!

**Comment by rolodato** [comment]
On second thought, I think it's better to add a `--production` flag and use staging as the default. That way it's more difficult to shoot yourself in the foot by getting ratelimited in production.

**Comment by rolodato** [comment]
@travismiller: I've finished making the changes I mentioned locally. I'm having issues with GitLab's API though, it's always returning a 400 with this response when trying to update the certificate for the domain:

```
{"message":{"certificate":["misses intermediates"]}}
```

I also get the same error if I manually get the production certificate+chain and key and paste them in GitLab's UI. Did this work for you before?

**Comment by travismiller** [comment]
I only received that error when submitting a staging certificate.

**Comment by travismiller** [comment]
Also, I agree with all of your suggestions.

**Comment by rolodato** [comment]
Good catch, I messed up my flags and was trying to use a staging certificate.

I pushed some changes and merged. Thanks very much for the contribution, much appreciated!

**Pull request merged**
